# .github/workflows/issue-labeling.yml
name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label-and-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Add reply and label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            if (issue && !issue.assignee) {
              await github.rest.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Thank you for reporting this issue. We will triage it as soon as possible.`
              });

              await github.rest.issues.addLabels({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Needs: Triage :mag:']
              });
            }
